### PR TITLE
Player collision

### PR DESCRIPTION
**Pull request by TheoBerlin**
The FPS player camera is represented by a capsule which collides with the world.

Phase 0:
`CameraSystem` reads keyboard and mouse input, writes to velocity component

Phase 1:
`PhysicsSystem` reads position and velocity, moves player capsule in the physics world, applies results to velocity

Phase 2:
`TransformApplier` performs `position += velocity`

### CODE REVIEW

**Review by skumbananaaa — APPROVED** [review]
Look Good! I am no good english!

**Comment by norda97** [comment]
> Look Good!

**Comment by Ceanze** [comment]
> Look Good!

**Comment by TheoBerlin** [comment]
Good Look!

**Review by Vonsen — APPROVED** [review]
Look Good!

**Comment by Mumsfilibaba** [comment]
> 



> Look Good!

You russian yes?

**Pull request merged**
